x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile.run
    args:
        CUSTOM_SSH_PORT: ${SSH_PORT}
        CUSTOM_UID: ${NANOBOT_UID}
        CUSTOM_GID: ${NANOBOT_GID}
  env_file:
    - .env
  volumes:
    - ~/.nanobot:/home/nanobot/.nanobot
    - ~/data/tmp/nanobot_cache/vscodium-server:/home/nanobot/.vscodium-server
    - ~/data/tmp/nanobot_cache/vscode-server:/home/nanobot/.vscode-server
    - ~/data/tmp/nanobot_cache/cache:/home/nanobot/.cache
    - ~/data/tmp/nanobot_cache/pyenv:/home/nanobot/.pyenv
  network_mode: host # host для wakeonlan
  # network_mode: bridge
  
services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:9972:2222
    #  - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
          devices:
            - driver: nvidia
              device_ids: ['${NVIDIA_VISIBLE_DEVICES}'] 
              capabilities: [gpu]  
  
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
